name = "lime-auth"
main = "src/worker/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "lime-auth"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"
